version: '3'

tasks:
  check:
    cmds:
      - odin check src
  run-rel:
    cmds:
      - odin run src -o:speed
  run:
    cmds:
      - odin run src
  check-leak:
    cmds:
      - odin build src -out:fovea
      - valgrind --leak-check=full ./fovea
      - rm fovea
