version: '3'

tasks:
  check:
    cmds:
      - odin check src
  run-rel:
    cmds:
      - odin run src -o:speed -- {{.CLI_ARGS}}
  run:
    cmds:
      - odin run src -- {{.CLI_ARGS}}
  check-leak:
    cmds:
      - odin build src -out:fovea 
      - valgrind --leak-check=full ./fovea {{.CLI_ARGS}}
      - rm fovea
